# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{pelt}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["russ bradberry", "matthew jording"]
  s.date = %q{2010-11-13}
  s.default_executable = %q{pelt}
  s.description = %q{A SASS/SCSS jQuery UI Port for Theme Management and Extensibility}
  s.email = %q{rbradberry@gmail.com}
  s.executables = ["pelt"]
  s.extra_rdoc_files = [
    "README"
  ]
  s.files = [
    "lib/pelt.rb",
     "lib/pelt/app_integration.rb",
     "lib/pelt/app_integration/rails.rb",
     "lib/pelt/cli.rb",
     "lib/pelt/commands.rb",
     "lib/pelt/commands/installer_command.rb",
     "lib/pelt/commands/registry.rb",
     "lib/pelt/installers.rb",
     "lib/pelt/installers/base.rb",
     "lib/pelt/sass_extensions/functions.rb",
     "lib/pelt/sass_extensions/functions/selectors.rb",
     "lib/pelt/sass_extentions.rb",
     "lib/pelt/settings.rb",
     "lib/pelt/ui.rb",
     "lib/pelt/version.rb"
  ]
  s.homepage = %q{http://github.com/nyc-ruby-meetup/pelt}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{A SASS/SCSS jQuery UI Port for Theme Management and Extensibility}
  s.test_files = [
    "spec/pelt_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_development_dependency(%q<ronn>, [">= 0"])
      s.add_development_dependency(%q<yard>, [">= 0"])
      s.add_runtime_dependency(%q<sass>, [">= 0"])
      s.add_runtime_dependency(%q<thor>, [">= 0"])
    else
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_dependency(%q<ronn>, [">= 0"])
      s.add_dependency(%q<yard>, [">= 0"])
      s.add_dependency(%q<sass>, [">= 0"])
      s.add_dependency(%q<thor>, [">= 0"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
    s.add_dependency(%q<ronn>, [">= 0"])
    s.add_dependency(%q<yard>, [">= 0"])
    s.add_dependency(%q<sass>, [">= 0"])
    s.add_dependency(%q<thor>, [">= 0"])
  end
end

