# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{pelt}
  s.version = "0.0.0.pre1"

  s.required_rubygems_version = Gem::Requirement.new("> 1.3.1") if s.respond_to? :required_rubygems_version=
  s.authors = ["russ bradberry", "matthew jording"]
  s.date = %q{2010-11-14}
  s.default_executable = %q{pelt}
  s.description = %q{A SASS/SCSS jQuery UI Port for Theme Management and Extensibility}
  s.email = %q{rbradberry@gmail.com}
  s.executables = ["pelt"]
  s.extra_rdoc_files = [
    "README"
  ]
  s.files = [
    "frameworks/jquery-ui/templates/sass/jquery-ui.scss",
    "frameworks/jquery-ui/templates/sass/partials/_jquery-ui-accordion.scss",
    "frameworks/jquery-ui/templates/sass/partials/_jquery-ui-all.scss",
    "frameworks/jquery-ui/templates/sass/partials/_jquery-ui-autocomplete.scss",
    "frameworks/jquery-ui/templates/sass/partials/_jquery-ui-base.scss",
    "frameworks/jquery-ui/templates/sass/partials/_jquery-ui-button.scss",
    "frameworks/jquery-ui/templates/sass/partials/_jquery-ui-core.scss",
    "frameworks/jquery-ui/templates/sass/partials/_jquery-ui-datepicker.scss",
    "frameworks/jquery-ui/templates/sass/partials/_jquery-ui-dialog.scss",
    "frameworks/jquery-ui/templates/sass/partials/_jquery-ui-progressbar.scss",
    "frameworks/jquery-ui/templates/sass/partials/_jquery-ui-resizable.scss",
    "frameworks/jquery-ui/templates/sass/partials/_jquery-ui-selectable.scss",
    "frameworks/jquery-ui/templates/sass/partials/_jquery-ui-slider.scss",
    "frameworks/jquery-ui/templates/sass/partials/_jquery-ui-tabs.scss",
    "frameworks/jquery-ui/templates/sass/partials/_jquery-ui-theme.scss"
  ]
  s.homepage = %q{http://github.com/nyc-ruby-meetup/pelt}
  s.require_paths = ["lib", "frameworks"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{A SASS/SCSS jQuery UI Port for Theme Management and Extensibility}
  s.test_files = [
    "spec/configurable/filesystem_aware.rb",
    "spec/pelt_spec.rb",
    "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_development_dependency(%q<yard>, [">= 0"])
      s.add_runtime_dependency(%q<sass>, [">= 0"])
      s.add_runtime_dependency(%q<thor>, [">= 0"])
    else
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_dependency(%q<yard>, [">= 0"])
      s.add_dependency(%q<sass>, [">= 0"])
      s.add_dependency(%q<thor>, [">= 0"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
    s.add_dependency(%q<yard>, [">= 0"])
    s.add_dependency(%q<sass>, [">= 0"])
    s.add_dependency(%q<thor>, [">= 0"])
  end
end

